---
title: "test"
output:
  word_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tximport)
library(rhdf5)

# to convert to Word document, type in Console >rmarkdown::render("file_name.Rmd")

```

## Test R Markdown

Looking at samples from merged reads that were over 20 million (exluding 2 MCF-7 samples and 3 SUM159 samples) and replotting PCA plots to see if any differences between low/high reads

### Transcript abundance import

```{r mcf txi}
# direct R Studio to folders where abundance.h5 files are stored

mcf_dir <- c("quant/MCF_DMSO_24H_1/", "quant/MCF_DMSO_24H_2/", "quant/MCF_DMSO_24H_3/", "quant/MCF_DMSO_7D_1/", "quant/MCF_DMSO_7D_2","quant/MCF_DMSO_7D_3/", "quant/MCF_SGC_24H_1/", "quant/MCF_SGC_24H_2/", "quant/MCF_SGC_24H_3/", "quant/MCF_SGC_7D_3/")

mcf_files <- list.files(path=mcf_dir, pattern="*.h5", full.names=TRUE)

# combine into one table

names(mcf_files) <- paste0("MCF", 1:10)

# read in kallisto type (transcript-level information)

txi.mcf_kallisto <- tximport(mcf_files, type = "kallisto", txOut=TRUE)
head(txi.mcf_kallisto$counts)

```

```{r sum txi}
# direct R Studio to folders where abundance.h5 files are stored

sum_dir <- c("quant/SUM_DMSO_24H_1/", "quant/SUM_DMSO_24H_2/", "quant/SUM_DMSO_7D_1/", "quant/SUM_DMSO_7D_2","quant/SUM_DMSO_7D_3/", "quant/SUM_SGC_24H_2/", "quant/SUM_SGC_24H_3/", "quant/SUM_SGC_7D_1/", "quant/SUM_SGC_7D_3/")

sum_files <- list.files(path=sum_dir, pattern="*.h5", full.names=TRUE)

# combine into one table

names(sum_files) <- paste0("SUM", 1:9)

# read in kallisto type (transcript-level information)

txi.sum_kallisto <- tximport(sum_files, type = "kallisto", txOut=TRUE)
head(txi.sum_kallisto$counts)

```

### MCF-7 PCA plots

```{r mcf metadata}

meta_data <- read.table("mcf_metadata.csv", sep=",", header = TRUE)

# remove 2 samples - row 10 and 11
metadata <- meta_data[-c(10,11), ]

rownames(metadata) <- metadata$Samples

colnames(txi.mcf_kallisto$counts) <- rownames(metadata)

all(rownames(metadata) %in% colnames(txi.mcf_kallisto$counts))

head(txi.mcf_kallisto$counts)

```

```{r mcf dds}

dds <- DESeqDataSetFromTximport(txi.mcf_kallisto, metadata, ~Condition)

vsd <- varianceStabilizingTransformation(dds, blind=FALSE)

```


```{r mcf pca}


plotPCA(vsd, intgroup=c("Condition"))

plotPCA(vsd, intgroup=c("Condition", "Samples"))

```


### SUM159 PCA plots

```{r sum metadata}

meta_data <- read.table("sum_metadata.csv", sep=",", header = TRUE)

# remove 3 samples - rows 3, 7 and 11
metadata <- meta_data[-c(3, 7, 11), ]

rownames(metadata) <- metadata$Samples

colnames(txi.sum_kallisto$counts) <- rownames(metadata)

all(rownames(metadata) %in% colnames(txi.sum_kallisto$counts))

head(txi.sum_kallisto$counts)

```

```{r sum dds}

dds <- DESeqDataSetFromTximport(txi.sum_kallisto, metadata, ~Condition)

vsd <- varianceStabilizingTransformation(dds, blind=FALSE)

```


```{r sum pca}


plotPCA(vsd, intgroup=c("Condition"))

plotPCA(vsd, intgroup=c("Condition", "Samples"))

```
