---
title: "key_hallmark_genes_LFC"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)

# if need to update packages but not sure which ones, update them all > update.packages(checkBuilt=TRUE)
```

# Key Hallmark Genes

Based on reading literature around hallmark gene set signatures, picked out interesting genes from papers and look up LFC for each clone.

```{r}
# read in total results (differentially expressed genes) for each clone

mcf1_res <- read.csv("MCF1_res.csv", header=TRUE)
mcf2_res <- read.csv("MCF2_res.csv", header=TRUE)
sum1_res <- read.csv("SUM1_res.csv", header=TRUE)
sum2_res <- read.csv("SUM2_res.csv", header=TRUE)

# read in list of interesting hallmark genes from literature

genes <- read.csv("hallmark_genes_literature.csv", header=TRUE)

# compare to each clone

mcf1 <- mcf1_res[is.element(mcf1_res$SYMBOL, genes$genes),]
mcf2 <- mcf2_res[is.element(mcf2_res$SYMBOL, genes$genes),]
sum1 <- sum1_res[is.element(sum1_res$SYMBOL, genes$genes),]
sum2 <- sum2_res[is.element(sum2_res$SYMBOL, genes$genes),]

# export lists

write.csv(mcf1, "key_hallmark_genes_lfc/mcf1.csv")
write.csv(mcf2, "key_hallmark_genes_lfc/mcf2.csv")
write.csv(sum1, "key_hallmark_genes_lfc/sum1.csv")
write.csv(sum2, "key_hallmark_genes_lfc/sum2.csv")
  
# select LFC and SYMBOL columns for each clone

mcf1 <- mcf1 %>% 
  select(SYMBOL, log2FoldChange)

mcf2 <- mcf2 %>% 
  select(SYMBOL, log2FoldChange)

sum1 <- sum1 %>% 
  select(SYMBOL, log2FoldChange)

sum2 <- sum2 %>% 
  select(SYMBOL, log2FoldChange)

# merge mcf lfc and rename columns

mcf <- merge(mcf1, mcf2, by="SYMBOL", all = TRUE)

mcf <- mcf %>% 
  mutate(mcf1_lfc = log2FoldChange.x, mcf2_lfc = log2FoldChange.y) %>% 
  select(-log2FoldChange.x, -log2FoldChange.y)

# merge sum lfc and rename columns

sum <- merge(sum1, sum2, by="SYMBOL", all = TRUE)

sum <- sum %>% 
  mutate(sum1_lfc = log2FoldChange.x, sum2_lfc = log2FoldChange.y) %>% 
  select(-log2FoldChange.x, -log2FoldChange.y)

# export files

write.csv(mcf, "key_hallmark_genes_lfc/mcf_lfc.csv")
write.csv(sum, "key_hallmark_genes_lfc/sum_lfc.csv")


```
